# Generated by Django 5.0.14 on 2025-10-13 06:17

import django.db.models.deletion
import voice_flow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=voice_flow.models.generate_api_key, max_length=128, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceFormConfig',
            fields=[
                ('form_id', models.CharField(default=voice_flow.models.generate_form_id, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fields', models.JSONField(help_text='Array of field definitions')),
                ('ai_prompt', models.TextField(help_text='Initial AI prompt for the conversation')),
                ('callback_url', models.URLField(help_text='Webhook URL to send completed data')),
                ('callback_method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT')], default='POST', max_length=10)),
                ('webhook_secret', models.CharField(default=voice_flow.models.generate_webhook_secret, max_length=128)),
                ('success_message', models.TextField(default='Thank you for completing the form!')),
                ('error_message', models.TextField(default='We encountered an error. Please try again.')),
                ('settings', models.JSONField(default=dict, help_text='Additional form settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='voice_flow.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagicLinkSession',
            fields=[
                ('session_id', models.CharField(default=voice_flow.models.generate_session_id, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('session_data', models.JSONField(default=dict, help_text='Custom data passed during link generation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=20)),
                ('collected_data', models.JSONField(default=dict, help_text='Data collected during the session')),
                ('conversation_history', models.JSONField(default=list, help_text='Full conversation transcript')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('fields_completed', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('webhook_response_code', models.IntegerField(blank=True, null=True)),
                ('webhook_sent_at', models.DateTimeField(blank=True, null=True)),
                ('form_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='voice_flow.voiceformconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('is_success', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='voice_flow.magiclinksession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='magiclinksession',
            index=models.Index(fields=['status', 'expires_at'], name='voice_flow__status_c80c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclinksession',
            index=models.Index(fields=['form_config', 'status'], name='voice_flow__form_co_ed69f5_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['session', 'created_at'], name='voice_flow__session_39675c_idx'),
        ),
    ]
