# Generated by Django 5.2.5 on 2025-09-30 05:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("form_schema", models.JSONField(default=dict)),
                ("magic_link_enabled", models.BooleanField(default=True)),
                ("magic_link_expiry_hours", models.IntegerField(default=24)),
                (
                    "callback_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to receive form data via POST",
                    ),
                ),
                (
                    "callback_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom headers for callback",
                    ),
                ),
                (
                    "callback_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for callback authentication",
                        max_length=200,
                    ),
                ),
                (
                    "ai_instructions",
                    models.TextField(
                        default="You are a professional assistant helping to collect information. Be friendly, clear, and ask one question at a time.",
                        help_text="Custom instructions for the AI assistant",
                    ),
                ),
                (
                    "ai_voice_name",
                    models.CharField(default="Puck", max_length=50),
                ),
                (
                    "ai_language",
                    models.CharField(default="en-US", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MagicLinkSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "magic_link_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("session_data", models.JSONField(default=dict)),
                (
                    "current_step",
                    models.CharField(default="start", max_length=50),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("callback_sent", models.BooleanField(default=False)),
                (
                    "callback_response",
                    models.JSONField(blank=True, default=dict),
                ),
                ("callback_error", models.TextField(blank=True)),
                (
                    "form_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voice_flow.formconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_data", models.JSONField()),
                (
                    "submission_timestamp",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("callback_attempts", models.IntegerField(default=0)),
                ("callback_delivered", models.BooleanField(default=False)),
                (
                    "callback_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "callback_response_code",
                    models.IntegerField(blank=True, null=True),
                ),
                ("callback_response_body", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voice_flow.magiclinksession",
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DynamicFormData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_value", models.TextField()),
                (
                    "field_type",
                    models.CharField(default="text", max_length=50),
                ),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_data",
                        to="voice_flow.magiclinksession",
                    ),
                ),
            ],
            options={
                "ordering": ["collected_at"],
                "unique_together": {("session", "field_name")},
            },
        ),
    ]
