# Generated by Django 5.2.5 on 2025-10-02 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclinksession',
            name='conversation_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='magiclinksession',
            name='form_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='voice_flow.formconfiguration'),
        ),
    ]
